/*CREATE TABLE [EBAY]
(
	[ITEMID] INT NOT NULL,
	[ITEM] NVARCHAR(200) NOT NULL,
	[ITEM DESCRIPTION] NVARCHAR(200) NOT NULL,
	[PRICE] INT NOT NULL, 
	CONSTRAINT [PK_EBAY] PRIMARY KEY CLUSTERED ([ITEMID])
);
GO
CREATE TABLE [ETSY]
(
	[ITEMID] INT NOT NULL,
	[ITEM] NVARCHAR(200) NOT NULL,
	[ITEM DESCRIPTION] NVARCHAR(200) NOT NULL,
	[PRICE] INT NOT NULL, 
	CONSTRAINT [PK_ETSY] PRIMARY KEY CLUSTERED ([ITEMID])
);
CREATE TABLE [AMAZON]
(
	[ITEMID] INT NOT NULL,
	[ITEM] NVARCHAR(200) NOT NULL,
	[ITEM DESCRIPTION] NVARCHAR(200) NOT NULL,
	[PRICE] INT NOT NULL, 
	CONSTRAINT [PK_AMAZON] PRIMARY KEY CLUSTERED ([ITEMID])
);
*/
/*Creating Customer Table*/
CREATE TABLE Customer
(
	CustomerId INT PRIMARY KEY IDENTITY,
	firstName NVARCHAR(200) NOT NULL,
	lastName NVARCHAR(200) NOT NULL,
	userName NVARCHAR(200) NOT NULL,
	customerPassword NVARCHAR(200) NOT NULL,
);
CREATE TABLE StoreLocations
(
	StoreID INT PRIMARY KEY IDENTITY,
	StoreName NVARCHAR(200) NOT NULL,
	StoreLocation NVARCHAR(200) NOT NULL,
);
CREATE TABLE Products
(
	ProductID INT PRIMARY KEY IDENTITY,
	ProductName NVARCHAR(200) NOT NULL,
	ProductDesc NVARCHAR(200) NOT NULL,
	ProductPrice DECIMAL NOT NULL
);
CREATE TABLE customerOrder
(
	orderID INT PRIMARY KEY IDENTITY,
	CustomerId INT NOT NULL FOREIGN KEY REFERENCES Customer(CustomerId) ON DELETE CASCADE,
	StoreID INT NOT NULL FOREIGN KEY REFERENCES StoreLocations(StoreID) ON DELETE CASCADE,
	ProductID INT NOT NULL FOREIGN KEY REFERENCES Products(ProductID) ON DELETE CASCADE,
	ProductQuantity INT NOT NULL,
	ProductPrice DECIMAL NOT NULL,
	TotalProductPrice AS CONVERT(DECIMAL(5, 2), ProductQuantity* ProductPrice)
);


/*POPULATE TABLES*/
INSERT INTO [dbo].[AMAZON] ([ITEMID], [ITEM], [ITEM DESCRIPTION], [PRICE]) VALUES (001, N'GOKU STICKER', N'FIVE STAR STUDIO DRAGON BALL GOKU STICKER-PEEL & PASTE(STICKS TO DRY SURFACES)', 10);
INSERT INTO [dbo].[AMAZON] ([ITEMID], [ITEM], [ITEM DESCRIPTION], [PRICE]) VALUES (002, N'VEGETA STICKER', N'FIVE STAR STUDIO DRAGON BALL VEGETA STICKER-PEEL & PASTE(STICKS TO DRY SURFACES)', 10);
INSERT INTO [dbo].[AMAZON] ([ITEMID], [ITEM], [ITEM DESCRIPTION], [PRICE]) VALUES (003, N'GOHAN STICKER', N'FIVE STAR STUDIO DRAGON BALL GOHAN STICKER-PEEL & PASTE(STICKS TO DRY SURFACES)', 10);
INSERT INTO [dbo].[AMAZON] ([ITEMID], [ITEM], [ITEM DESCRIPTION], [PRICE]) VALUES (004, N'BAKUGO STICKER', N'FIVE STAR STUDIO MY HERO ACADEMIA BAKUGO STICKER-PEEL & PASTE(STICKS TO DRY SURFACES)', 10);
INSERT INTO [dbo].[AMAZON] ([ITEMID], [ITEM], [ITEM DESCRIPTION], [PRICE]) VALUES (005, N'ALL MIGHT STICKER', N'FIVE STAR STUDIO MY HERO ACADEMIA ALL MIGHT STICKER-PEEL & PASTE(STICKS TO DRY SURFACES)', 10);

INSERT INTO [dbo].[EBAY] ([ITEMID], [ITEM], [ITEM DESCRIPTION], [PRICE]) VALUES (001, N'GOKU STICKER', N'FIVE STAR STUDIO DRAGON BALL GOKU STICKER-PEEL & PASTE(STICKS TO DRY SURFACES)', 10);
INSERT INTO [dbo].[EBAY] ([ITEMID], [ITEM], [ITEM DESCRIPTION], [PRICE]) VALUES (002, N'VEGETA STICKER', N'FIVE STAR STUDIO DRAGON BALL VEGETA STICKER-PEEL & PASTE(STICKS TO DRY SURFACES)', 10);
INSERT INTO [dbo].[EBAY] ([ITEMID], [ITEM], [ITEM DESCRIPTION], [PRICE]) VALUES (003, N'GOHAN STICKER', N'FIVE STAR STUDIO DRAGON BALL GOHAN STICKER-PEEL & PASTE(STICKS TO DRY SURFACES)', 10);
INSERT INTO [dbo].[EBAY] ([ITEMID], [ITEM], [ITEM DESCRIPTION], [PRICE]) VALUES (004, N'BAKUGO STICKER', N'FIVE STAR STUDIO MY HERO ACADEMIA BAKUGO STICKER-PEEL & PASTE(STICKS TO DRY SURFACES)', 10);
INSERT INTO [dbo].[EBAY] ([ITEMID], [ITEM], [ITEM DESCRIPTION], [PRICE]) VALUES (005, N'ALL MIGHT STICKER', N'FIVE STAR STUDIO MY HERO ACADEMIA ALL MIGHT STICKER-PEEL & PASTE(STICKS TO DRY SURFACES)', 10);

INSERT INTO [dbo].[ETSY] ([ITEMID], [ITEM], [ITEM DESCRIPTION], [PRICE]) VALUES (001, N'GOKU STICKER', N'FIVE STAR STUDIO DRAGON BALL GOKU STICKER-PEEL & PASTE(STICKS TO DRY SURFACES)', 10);
INSERT INTO [dbo].[ETSY] ([ITEMID], [ITEM], [ITEM DESCRIPTION], [PRICE]) VALUES (002, N'VEGETA STICKER', N'FIVE STAR STUDIO DRAGON BALL VEGETA STICKER-PEEL & PASTE(STICKS TO DRY SURFACES)', 10);
INSERT INTO [dbo].[ETSY] ([ITEMID], [ITEM], [ITEM DESCRIPTION], [PRICE]) VALUES (003, N'GOHAN STICKER', N'FIVE STAR STUDIO DRAGON BALL GOHAN STICKER-PEEL & PASTE(STICKS TO DRY SURFACES)', 10);
INSERT INTO [dbo].[ETSY] ([ITEMID], [ITEM], [ITEM DESCRIPTION], [PRICE]) VALUES (004, N'BAKUGO STICKER', N'FIVE STAR STUDIO MY HERO ACADEMIA BAKUGO STICKER-PEEL & PASTE(STICKS TO DRY SURFACES)', 10);
INSERT INTO [dbo].[ETSY] ([ITEMID], [ITEM], [ITEM DESCRIPTION], [PRICE]) VALUES (005, N'ALL MIGHT STICKER', N'FIVE STAR STUDIO MY HERO ACADEMIA ALL MIGHT STICKER-PEEL & PASTE(STICKS TO DRY SURFACES)', 10);

INSERT INTO dbo.StoreLocations (StoreID, StoreName, StoreLocation) VALUES (001, N'Amazon', 'NStoreLocation');